id: P000466
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21765
  title: ཐོག་ཁང་དམར་པོའི་རྨི་ལམ།
  author: ''
  volumes:
    2be1434453774832a871448816cb0edd:
      image_group_id: I1KG21234
      title: Volume 1 of thog khang dmar po'i rmi lam/
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
